# Generated by Django 5.1.4 on 2025-01-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_image_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartitem',
        ),
    ]
