# Generated by Django 5.1.4 on 2025-01-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
